image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

environment:
  matrix:
    - db: MySQL

    - db: PostgreSQL

for:
  -
    matrix:
      only:
        - db: MySQL

    install:
      - sudo curl -SL https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - sudo docker-compose -f /home/appveyor/projects/qa-diplom/docker-compose.yml up -d
      - sleep 20
      - java -jar artifacts/aqa-shop.jar --spring.datasource.url=jdbc:mysql://185.119.57.176:3306/base_mysql &
      - sleep 20

    build_script:
      - chmod +x gradlew
      - ./gradlew test --info -Dselenide.headless=true -Ddatasource=jdbc:mysql://185.119.57.176:3306/base_mysql 
      - sudo docker-compose down

  -
    matrix:
      only:
        - db: PostgreSQL

    install:
      - sudo curl -SL https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - sudo docker-compose -f /home/appveyor/projects/qa-diplom/docker-compose.yml up -d
      - sleep 20
      - java -jar artifacts/aqa-shop.jar --spring.datasource.url=jdbc:postgresql://185.119.57.176:5432/base_postgresql &
      - sleep 20

    build_script:
      - chmod +x gradlew
      - ./gradlew test --info -Dselenide.headless=true -Ddatasource=jdbc:postgresql://185.119.57.176:5432/base_postgresql
      - sudo docker-compose down
